services:
  e2e:
    build:
      context: .
      target: e2e
      network: host
    env_file: .env
    environment:
      PANDORA_E2E_URL: http://web:8000
      DJANGO_SETTINGS_MODULE: pandora.web.settings
    depends_on:
      web:
        condition: service_healthy
    entrypoint: ["pytest", "e2e", "-q"]
