# Generated by Django 6.0.8 on 2026-08-29 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_servicelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("field", models.CharField(max_length=100)),
                ("pattern", models.CharField(max_length=500)),
                ("active", models.BooleanField(default=True)),
                ("dropped", models.PositiveBigIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_rules",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [models.Index(fields=["active"], name="scrub_drop_active")],
            },
        ),
        migrations.CreateModel(
            name="ScrubRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=500)),
                (
                    "action",
                    models.CharField(
                        choices=[("remove", "Remove"), ("mask", "Mask")],
                        default="remove",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrub_rules",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [models.Index(fields=["active"], name="scrub_rule_active")],
            },
        ),
    ]
