# Generated by Django 6.0.8 on 2026-08-29 21:51

import django.db.models.deletion
import pandora.notify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_servicelink"),
        ("issues", "0006_issue_snoozed_past_count_issue_snoozed_until_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                            ("teams", "Microsoft Teams"),
                        ],
                        default="webhook",
                        max_length=16,
                    ),
                ),
                (
                    "target",
                    models.TextField(
                        help_text="Webhook or chat URL, or a comma-separated list of email addresses"
                    ),
                ),
                ("secret", models.CharField(blank=True, default="", max_length=200)),
                (
                    "events",
                    models.JSONField(
                        blank=True, default=pandora.notify.models.default_events
                    ),
                ),
                (
                    "min_level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("fatal", "Fatal"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("digest_seconds", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("send_after", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="issues.issue",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notify.destination",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="destination",
            index=models.Index(fields=["enabled"], name="notify_dest_enabled"),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["state", "created_at"], name="notify_delivery_state"
            ),
        ),
    ]
