# Generated by Django 6.0.7 on 2026-08-04 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_events', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['seen_at'], name='ingest_processed_seen')],
                'constraints': [models.UniqueConstraint(fields=('project', 'event_id'), name='ingest_processed_event_uq')],
            },
        ),
        migrations.CreateModel(
            name='RawEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('am', 'Alertmanager'), ('sdk', 'SDK')], max_length=8)),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('error', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'received_at'], name='ingest_env_state_recv')],
            },
        ),
    ]
