# Generated by Django 6.0.8 on 2026-08-29 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_servicelink"),
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("bucket", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["bucket"], name="ingest_counter_bucket")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "bucket"), name="ingest_counter_key_bucket_uq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("limit", models.PositiveIntegerField()),
                ("window_seconds", models.PositiveIntegerField(default=60)),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotas",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["active"], name="ingest_quota_active")
                ],
            },
        ),
    ]
