# Generated by Django 6.0.8 on 2026-08-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_ingestcounter_ingestquota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawenvelope",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("claimed", "Claimed"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
