# Generated by Django 6.0.8 on 2026-08-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_token_sources"),
        ("ingest", "0003_envelope_claimed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawenvelope",
            name="source",
            field=models.CharField(
                choices=[
                    ("am", "Alertmanager"),
                    ("sdk", "SDK"),
                    ("log", "Log lines"),
                    ("cron", "Cron check-ins"),
                    ("otlp", "OpenTelemetry"),
                ],
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("interval_minutes", models.PositiveIntegerField(default=60)),
                ("margin_minutes", models.PositiveIntegerField(default=5)),
                ("max_runtime_minutes", models.PositiveIntegerField(default=30)),
                (
                    "environment",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("in_progress", "In progress"),
                            ("missed", "Missed"),
                            ("error", "Error"),
                            ("timed_out", "Timed out"),
                        ],
                        default="ok",
                        max_length=16,
                    ),
                ),
                ("last_check_in", models.DateTimeField(blank=True, null=True)),
                ("last_started", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("slug",),
                "indexes": [
                    models.Index(
                        fields=["active", "status"], name="ingest_monitor_active"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "slug"), name="ingest_monitor_slug_uq"
                    )
                ],
            },
        ),
    ]
