# Generated by Django 6.0.8 on 2026-08-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0004_monitor"),
        ("issues", "0016_user_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedevent",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_events",
                to="issues.issue",
            ),
        ),
    ]
