# Generated by Django 6.0.8 on 2026-08-30 03:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_token_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debug_id", models.CharField(max_length=64)),
                ("release", models.CharField(blank=True, default="", max_length=250)),
                ("dist", models.CharField(blank=True, default="", max_length=100)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_bundles",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at",),
            },
        ),
        migrations.CreateModel(
            name="BundleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("source_map", "Source map"),
                            ("minified", "Minified source"),
                            ("source", "Original source"),
                        ],
                        default="source_map",
                        max_length=16,
                    ),
                ),
                ("blob", models.FileField(upload_to="artifacts/")),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha1", models.CharField(blank=True, default="", max_length=40)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="artifacts.artifactbundle",
                    ),
                ),
            ],
            options={
                "ordering": ("path",),
            },
        ),
        migrations.AddIndex(
            model_name="artifactbundle",
            index=models.Index(fields=["last_used_at"], name="artifacts_bundle_used"),
        ),
        migrations.AddConstraint(
            model_name="artifactbundle",
            constraint=models.UniqueConstraint(
                fields=("project", "debug_id"), name="artifacts_bundle_debug_id_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="bundlefile",
            index=models.Index(fields=["bundle", "kind"], name="artifacts_file_kind"),
        ),
    ]
