# Generated by Django 6.0.8 on 2026-08-30 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0001_initial"),
        ("core", "0005_token_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checksum", models.CharField(max_length=40)),
                ("blob", models.FileField(upload_to="chunks/")),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_chunks",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("received_at",),
                "indexes": [
                    models.Index(
                        fields=["received_at"], name="artifacts_chunk_received"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "checksum"), name="artifacts_chunk_uq"
                    )
                ],
            },
        ),
    ]
