apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pandora-kind
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pandora-kind-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pandora-kind
  hostPath:
    path: /var/local/pandora-kind
    type: DirectoryOrCreate
