# Generated by Django 6.0.7 on 2026-08-04 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=64)),
                ('fingerprint', models.JSONField(blank=True, default=list)),
                ('grouping_labels', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=500)),
                ('culprit', models.CharField(blank=True, default='', max_length=500)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], default='error', max_length=16)),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_count', models.PositiveBigIntegerField(default=0)),
                ('open_episode_count', models.PositiveIntegerField(default=0)),
                ('source_state', models.CharField(blank=True, choices=[('firing', 'Firing'), ('resolved', 'Resolved')], max_length=16, null=True)),
                ('triage_state', models.CharField(choices=[('new', 'New'), ('ack', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='new', max_length=16)),
                ('last_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.project')),
            ],
            options={
                'ordering': ('-last_seen',),
            },
        ),
        migrations.CreateModel(
            name='HourlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_fingerprint', models.CharField(max_length=64)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_count', models.PositiveIntegerField(default=1)),
                ('last_delivery_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.project')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='issues.issue')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('regression', 'Regression'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('reopened', 'Reopened'), ('silenced', 'Silenced'), ('unsilenced', 'Unsilenced'), ('regrouped', 'Regrouped')], max_length=32)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='issues.issue')),
            ],
            options={
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='SilenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_silence_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='TagStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField(default=0)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_stats', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='GroupingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100)),
                ('alertname_regex', models.CharField(blank=True, default='', max_length=200)),
                ('mode', models.CharField(choices=[('denylist', 'Denylist'), ('allowlist', 'Allowlist')], default='denylist', max_length=16)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grouping_rules', to='core.project')),
            ],
            options={
                'ordering': ('priority', 'id'),
                'indexes': [models.Index(fields=['active', 'priority'], name='issues_rule_active_prio')],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'triage_state', '-last_seen'], name='issues_issue_proj_triage'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'source_state'], name='issues_issue_proj_source'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint_hash'), name='issues_issue_fingerprint_uq'),
        ),
        migrations.AddIndex(
            model_name='hourlystat',
            index=models.Index(fields=['issue', '-hour'], name='issues_hourly_issue_hour'),
        ),
        migrations.AddConstraint(
            model_name='hourlystat',
            constraint=models.UniqueConstraint(fields=('issue', 'hour'), name='issues_hourly_issue_hour_uq'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['issue', '-starts_at'], name='issues_episode_issue_start'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(condition=models.Q(('ends_at__isnull', True)), fields=['project', 'am_fingerprint'], name='issues_episode_open'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('project', 'am_fingerprint', 'starts_at'), name='issues_episode_identity_uq'),
        ),
        migrations.AddIndex(
            model_name='issueactivity',
            index=models.Index(fields=['issue', '-at'], name='issues_activity_issue_at'),
        ),
        migrations.AddIndex(
            model_name='silencelink',
            index=models.Index(fields=['expires_at'], name='issues_silence_expires'),
        ),
        migrations.AddConstraint(
            model_name='silencelink',
            constraint=models.UniqueConstraint(fields=('issue', 'am_silence_id'), name='issues_silence_issue_am_uq'),
        ),
        migrations.AddIndex(
            model_name='tagstat',
            index=models.Index(fields=['issue', 'key', '-count'], name='issues_tag_issue_key_count'),
        ),
        migrations.AddConstraint(
            model_name='tagstat',
            constraint=models.UniqueConstraint(fields=('issue', 'key', 'value'), name='issues_tag_issue_key_value_uq'),
        ),
    ]
