# Generated by Django 6.0.7 on 2026-08-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("issues", "0002_default_grouping_rule"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="issue",
            name="issues_issue_fingerprint_uq",
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.UniqueConstraint(
                fields=("project", "environment", "fingerprint_hash"),
                name="issues_issue_fingerprint_uq",
            ),
        ),
    ]
