# Generated by Django 6.0.7 on 2026-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("issues", "0003_remove_issue_issues_issue_fingerprint_uq_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                condition=models.Q(("ends_at__isnull", True)),
                fields=["issue", "starts_at"],
                name="issues_episode_issue_open",
            ),
        ),
    ]
