# Generated by Django 6.0.8 on 2026-08-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_servicelink"),
        ("issues", "0005_deny_job_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="snoozed_past_count",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="snoozed_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issueactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("snoozed", "Snoozed"),
                    ("unsnoozed", "Woke up"),
                    ("regression", "Regression"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                    ("ignored", "Ignored"),
                    ("reopened", "Reopened"),
                    ("silenced", "Silenced"),
                    ("unsilenced", "Unsilenced"),
                    ("regrouped", "Regrouped"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["snoozed_until"], name="issues_issue_snoozed"),
        ),
    ]
