# Generated by Django 6.0.8 on 2026-08-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_issue_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="grouping_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="issues.groupingrule",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="grouping_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rule", "A grouping rule"),
                    ("default", "The built-in denylist"),
                    ("stack", "The exception's stack signature"),
                    ("logentry", "The log message template"),
                    ("message", "The message"),
                    ("client", "A fingerprint the client declared"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
