# Generated by Django 6.0.8 on 2026-08-30 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_ingesttoken_scope"),
        ("issues", "0008_grouping_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pattern", models.CharField(max_length=500)),
                (
                    "replacement",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("ordering", models.IntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_rules",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering", "id"),
                "indexes": [
                    models.Index(
                        fields=["active", "ordering"], name="issues_path_active_prio"
                    )
                ],
            },
        ),
    ]
