# Generated by Django 6.0.8 on 2026-08-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_path_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupingrule",
            name="conditions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="groupingrule",
            name="fingerprint",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="groupingrule",
            name="title_template",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
