# Generated by Django 6.0.8 on 2026-08-30 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_ingesttoken_scope"),
        ("issues", "0010_rule_conditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint_hash", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="issues.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_aliases",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("fingerprint_hash",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "fingerprint_hash"),
                        name="issues_alias_fingerprint_uq",
                    )
                ],
            },
        ),
    ]
