# Generated by Django 6.0.8 on 2026-08-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_issue_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("snoozed", "Snoozed"),
                    ("unsnoozed", "Woke up"),
                    ("regression", "Regression"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                    ("ignored", "Ignored"),
                    ("reopened", "Reopened"),
                    ("merged", "Merged"),
                    ("unmerged", "Unmerged"),
                    ("silenced", "Silenced"),
                    ("unsilenced", "Unsilenced"),
                    ("regrouped", "Regrouped"),
                ],
                max_length=32,
            ),
        ),
    ]
