# Generated by Django 6.0.8 on 2026-08-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0012_merge_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuealias",
            name="grouping_labels",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
