# Generated by Django 6.0.8 on 2026-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0013_alias_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("query", models.CharField(blank=True, default="", max_length=500)),
                ("sort", models.CharField(blank=True, default="", max_length=32)),
                ("ordering", models.IntegerField(default=100)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ordering", "name"),
            },
        ),
    ]
