# Generated by Django 6.0.8 on 2026-08-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0014_saved_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
