# Generated by Django 6.0.8 on 2026-08-30 02:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_token_sources"),
        ("issues", "0015_issue_search_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports",
                        to="issues.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at",),
                "indexes": [
                    models.Index(
                        fields=["project", "event_id"], name="issues_report_event"
                    ),
                    models.Index(
                        fields=["-received_at"], name="issues_report_received"
                    ),
                ],
            },
        ),
    ]
