# Generated by Django 6.0.7 on 2026-08-04 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='IngestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('source', models.CharField(choices=[('am', 'Alertmanager'), ('sdk', 'SDK')], default='am', max_length=8)),
                ('scope', models.CharField(choices=[('ingest', 'Ingest'), ('read', 'Read')], default='ingest', max_length=8)),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'scope', 'active'], name='core_token_src_scope')],
            },
        ),
        migrations.CreateModel(
            name='DsnKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsn_keys', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'active'], name='core_dsnkey_proj_active')],
            },
        ),
    ]
