# Generated by Django 6.0.8 on 2026-08-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url_template", models.TextField()),
                ("ordering", models.IntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering", "name"),
                "indexes": [
                    models.Index(
                        fields=["active", "ordering"], name="core_link_active_order"
                    )
                ],
            },
        ),
    ]
