# Generated by Django 6.0.8 on 2026-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_servicelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingesttoken",
            name="scope",
            field=models.CharField(
                choices=[
                    ("ingest", "Ingest"),
                    ("read", "Read"),
                    ("payload", "Read with payloads"),
                ],
                default="ingest",
                max_length=16,
            ),
        ),
    ]
