# Generated by Django 6.0.8 on 2026-08-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_ingesttoken_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="resolve_on_deploy",
            field=models.BooleanField(default=False),
        ),
    ]
