# Generated by Django 6.0.8 on 2026-08-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_resolve_on_deploy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingesttoken",
            name="source",
            field=models.CharField(
                choices=[
                    ("am", "Alertmanager"),
                    ("sdk", "SDK"),
                    ("log", "Log lines"),
                    ("cron", "Cron check-ins"),
                    ("otlp", "OpenTelemetry"),
                ],
                default="am",
                max_length=8,
            ),
        ),
    ]
