# Generated by Django 6.0.8 on 2026-08-30 01:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_ingesttoken_scope"),
        ("issues", "0015_issue_search_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=250)),
                ("dist", models.CharField(blank=True, default="", max_length=100)),
                ("sort_key", models.CharField(blank=True, default="", max_length=64)),
                ("parsed", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_key", "first_seen"),
            },
        ),
        migrations.CreateModel(
            name="Deploy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environment",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed out"),
                        ],
                        default="started",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deploys",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ReleaseEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_key", models.CharField(blank=True, default="", max_length=64)),
                ("in_next", models.BooleanField(default=False)),
                ("actor", models.CharField(blank=True, default="", max_length=150)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution",
                        to="issues.issue",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions",
                        to="releases.release",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["project", "sort_key"], name="releases_proj_sort"
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                fields=("project", "version", "dist"),
                name="releases_release_version_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="deploy",
            index=models.Index(fields=["-started_at"], name="releases_deploy_started"),
        ),
        migrations.AddConstraint(
            model_name="releaseenvironment",
            constraint=models.UniqueConstraint(
                fields=("release", "name"), name="releases_release_environment_uq"
            ),
        ),
    ]
