# Generated by Django 6.0.8 on 2026-08-30 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_resolve_on_deploy"),
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=250)),
                (
                    "environment",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("hour", models.DateTimeField()),
                ("sort_key", models.CharField(blank=True, default="", max_length=64)),
                ("parsed", models.BooleanField(default=False)),
                ("sessions", models.PositiveBigIntegerField(default=0)),
                ("crashed", models.PositiveBigIntegerField(default=0)),
                ("errored", models.PositiveBigIntegerField(default=0)),
                ("abnormal", models.PositiveBigIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_buckets",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-hour",),
                "indexes": [
                    models.Index(
                        fields=["project", "-hour"], name="releases_session_hour"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "version", "environment", "hour"),
                        name="releases_session_bucket_uq",
                    )
                ],
            },
        ),
    ]
